export const UPDATE_FETCH_USERS__SUCCESS= "UPDATE_FETCH_USERS__SUCCESS";
export const UPDATE_FETCH_MILESTONES__SUCCESS = "UPDATE_FETCH_MILESTONES__SUCCESS";

export const UPDATE_FETCH_PHRASE__START = "UPDATE_FETCH_PHRASE__START";
export const UPDATE_FETCH_PHRASE__SUCCESS = "UPDATE_FETCH_PHRASE__SUCCESS";
export const UPDATE_FETCH_PHRASE__FAILURE = "UPDATE_FETCH_PHRASE__FAILURE";

export const UPDATE_FETCH_LABEL__START = "UPDATE_FETCH_LABEL__START";
export const UPDATE_FETCH_LABEL__SUCCESS = "UPDATE_FETCH_LABEL__SUCCESS";
export const UPDATE_FETCH_LABEL__FAILURE = "UPDATE_FETCH_LABEL__FAILURE";

export const GITHUB_ISSUE_SEARCH_API = 'https://api.github.com/search/issues?q=repo:uber/react-vis';
